// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC03Bx6Hvxc04Hr_ENFcw65X_vUDzZAL9w',
    appId: '1:775433022639:web:c3b535bcbd810b60fe785a',
    messagingSenderId: '775433022639',
    projectId: 'projectexample-85877',
    authDomain: 'projectexample-85877.firebaseapp.com',
    storageBucket: 'projectexample-85877.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGCCfr1m7WoN7Syc0nHohVoFC1xWsZv0',
    appId: '1:775433022639:android:156dddee49c9b460fe785a',
    messagingSenderId: '775433022639',
    projectId: 'projectexample-85877',
    storageBucket: 'projectexample-85877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNVNGnB-l11SaqbYaQwPhG_H0irG4-i1A',
    appId: '1:775433022639:ios:9b4df729a6633276fe785a',
    messagingSenderId: '775433022639',
    projectId: 'projectexample-85877',
    storageBucket: 'projectexample-85877.appspot.com',
    iosClientId: '775433022639-qitjj3a2r29684qrgda43dkneuqjpmli.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHotelBookingUi',
  );
}
