// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabye8hWU4TmPPYpMHb8qPsJ8B4RQQpWc',
    appId: '1:611382992367:web:6a33d33e674dbb123d6a1a',
    messagingSenderId: '611382992367',
    projectId: 'project-magang-e4f19',
    authDomain: 'project-magang-e4f19.firebaseapp.com',
    storageBucket: 'project-magang-e4f19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9CuEVkENyuOj8NmroyJtAoBmejm5h5o',
    appId: '1:611382992367:android:978febc52bc667683d6a1a',
    messagingSenderId: '611382992367',
    projectId: 'project-magang-e4f19',
    storageBucket: 'project-magang-e4f19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCimKXYtyxWKdht0cBbtnKiId93wlnEsdI',
    appId: '1:611382992367:ios:8868191c71f172ec3d6a1a',
    messagingSenderId: '611382992367',
    projectId: 'project-magang-e4f19',
    storageBucket: 'project-magang-e4f19.appspot.com',
    iosClientId: '611382992367-p45tgt7viuhuf3cqmnnopi5nbvkdqpr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHotelBookingUi',
  );
}
